<?php
/**
 * PHPPremailer\PremailerException
 *
 * @author      Justin Lau
 * @copyright   Copyright (c) 2013 Justin Lau <justin@tclau.com>
 * @version     0.1
 * @license     MIT
 *
 * For the full copyright and license information, please view the LICENSE file that was distributed
 * with this package.
 */

namespace PHPPremailer;

use \Exception;

/**
 * An instance of this class represents an exception generated by PHPPremailer
 */
class PremailerException extends Exception {

	/**
	 * Create a new PremailerException instance.
	 *
	 * @param  string    $message
	 * @param  int       $code
	 * @param  Exception $previous
	 * @return self
	 */
	public function __construct($message, $code = 0, Exception $previous = null)
	{
		parent::__construct($message, $code, $previous);
	}
}